apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app-green
  namespace: boardgame-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame-app
      version: green
  template:
    metadata:
      labels:
        app: boardgame-app
        version: green
    spec:
      imagePullSecrets:  
        - name: docker-hub-secret
      containers:
        - name: boardgame-app
          image: docker.io/guihadyossry/boardgame-app:latest
          ports:
            - containerPort: 8080

