apiVersion: v1
kind: Service
metadata:
  name: boardgame-app-service
  namespace: boardgame-app
spec:
  selector:
    app: boardgame-app
    version: blue  # Initially pointing to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

