apiVersion: v1
kind: Service
metadata:
  name: boardgame-app-blue-service
  namespace: boardgame-app-cicd
spec:
  selector:
    app: boardgame-app
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
