apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app-green
  namespace: boardgame-app-cicd
  labels:
    app: boardgame-app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame-app
      version: green
  template:
    metadata:
      labels:
        app: boardgame-app
        version: green
    spec:
      containers:
        - name: boardgame-app
          image: docker.io/guihadyossry/boardgame-app:non-existent
          ports:
            - containerPort: 8080
