apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  namespace: boardgame-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: guihadyossry/boardgame-app:IMAGE_TAG  # This is replaced dynamically
          ports:
            - containerPort: 8080
