apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boardgame-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: boardgame-app
  namespaceSelector:
    matchNames:
      - boardgame-app-cicd
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
